use pizzeria;
db.provincies.insert([
    {
        _id:1,
        nom:"Barcelona"
    },
    {
        _id:2,
        nom:"Girona"
    },
    {
        _id:3,
        nom:"Tarragona"
    },
    {
        _id:4,
        nom:"Lleida"
    }
]);
db.localitats.insert([
    {
        _id:1,
        nom:"Barcelona",
        id_provincia:1
    },
    {
        _id:2,
        nom:"Badalona",
        id_provincia:1
    },
    {
        _id:3,
        nom:"Mataró",
        id_provincia:1
    },
    {
        _id:4,
        nom:"Girona",
        id_provincia:2
    },
    {
        _id:5,
        nom:"Figueres",
        id_provincia:2
    },
    {
        _id:6,
        nom:"Palamós",
        id_provincia:2
    },
    {
        _id:7,
        nom:"Tarragona",
        id_provincia:3
    },
    {
        _id:8,
        nom:"Amposta",
        id_provincia:3
    },
    {
        _id:9,
        nom:"Reus",
        id_provincia:3
    },
    {
        _id:10,
        nom:"Lleida",
        id_provincia:4
    },
    {
        _id:11,
        nom:"Tremp",
        id_provincia:4
    },
    {
        _id:12,
        nom:"Sort",
        id_provincia:4
    }
]);
db.botigues.insert([
    {
        "_id":1,
        "adreça":{
            "carrer":"Entença", 
            "cp":"08111",
            "id_localitat":1,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":2,
        "adreça":{
            "carrer":"Diagonal",
            "cp": "08111", 
            "id_localitat":1,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":3,
        "adreça":{
            "carrer":"March", 
            "cp":"08222", 
            "id_localitat":1,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":4,
        "adreça":{
            "carrer":"Prim",
            "cp": "08222", 
            "id_localitat":2,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":5,
        "adreça":{
            "carrer":"Sant Joan",
            "cp": "08222", 
            "id_localitat":2,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":6,
        "adreça":{
            "carrer":"Sant Pere", 
            "cp":"08333", 
            "id_localitat":3,
            "id_provincia":1
        }        
    }
    ,
    {
        "_id":7,
        "adreça":{
            "carrer":"1 de Maig", 
            "cp":"09111", 
            "id_localitat":4,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":8,
        "adreça":{
            "carrer":"Valencia",
            "cp": "09111",
            "id_localitat":4,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":9,
        "adreça":{
            "carrer": "Diputació",
            "cp": "09222", 
            "id_localitat":5,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":10,
        "adreça":{
            "carrer":"Aragó", 
            "cp":"09222",
            "id_localitat":5,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":11,
        "adreça":{
            "carrer":"Mallorca",
            "cp": "09333", 
            "id_localitat":6,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":12,
        "adreça":{
            "carrer":"Casanova",
            "cp": "09333", 
            "id_localitat":6,
            "id_provincia":2
        }        
    }
    ,
    {
        "_id":13,
        "adreça":{
            "carrer": "Londres", 
            "cp":"06333", 
            "id_localitat":12,
            "id_provincia":4
        }        
    }
    ,
    {
        "_id":14,
        "adreça":{
            "carrer":"Villaroel",
            "cp": "07111", 
            "id_localitat":7,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":15,
        "adreça":{
            "carrer":"Sepulveda",
            "cp": "07111", 
            "id_localitat":7,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":16,
        "adreça":{
            "carrer":"Floridablanca", 
            "cp":"07222", 
            "id_localitat":8,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":17,
        "adreça":{
            "carrer": "Paris",
            "cp": "06333", 
            "id_localitat":12,
            "id_provincia":4
        }        
    }
    ,
    {
        "_id":18,
        "adreça":{
            "carrer":"Aribau",
            "cp": "07222", 
            "id_localitat":8,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":19,
        "adreça":{
            "carrer":"Muntaner", 
            "cp":"07333", 
            "id_localitat":9,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":20,
        "adreça":{
            "carrer": "Balmes",
            "cp": "07333", 
            "id_localitat":9,
            "id_provincia":3
        }        
    }
    ,
    {
        "_id":21,
        "adreça":{
            "carrer":"Villaroel",
            "cp": "06111", 
            "id_localitat":10,
            "id_provincia":4
        }        
    }
    ,
    {
        "_id":22,
        "adreça":{
            "carrer":"Avenir",
            "cp": "06111", 
            "id_localitat":10,
            "id_provincia":4
        }        
    }
    ,
    {
        "_id":23,
        "adreça":{
            "carrer": "Gràcia", 
            "cp":"06222", 
            "id_localitat":11,
            "id_provincia":4
        }        
    }
    ,
    {
        "_id":24,
        "adreça":{
            "carrer": "Rosselló",
            "cp":"06222", 
            "id_localitat":11,
            "id_provincia":4
        }        
    }   
]);
db.clients.insert([
    {
        "_id":1,
        "nom":"Pere", 
        "cognom":"Aragones",
        "adreça":{
            "carrer":"Pere IV", 
            "cp":"08911", 
            "id_localitat":1,
            "id_provincia":1
        },
        "telèfon":"933994567"
    },
    {
        "_id":2,
        "nom":"Peret",
        "cognom": "Felop",
        "adreça":{
            "carrer":"Ricart", 
            "cp":"08922", 
            "id_localitat":1,
            "id_provincia":1
        },
        "telèfon":"933994545"
    },
    {
        "_id":3,
        "nom":"Luis", 
        "cognom":"Piar",
        "adreça":{
            "carrer":"Lluria", 
            "cp":"08933", 
            "id_localitat":2,
            "id_provincia":1
        },
        "telèfon":"933923232"
    },
    {
        "_id":4,
        "nom":"Maria",
        "cognom": "Juan",
        "adreça":{
            "carrer":"Roger", 
            "cp":"08944", 
            "id_localitat":2,
            "id_provincia":1
        },
        "telèfon":"933991111"
    },
    {
        "_id":5,
        "nom":"Joan", 
        "cognom":"Haitd",
        "adreça":{
            "carrer":"Ramis", 
            "cp":"08955", 
            "id_localitat":3,
            "id_provincia":1
        },
        "telèfon":"933992222"
    },
    {
        "_id":6,
        "nom":"Ramon",
        "cognom": "James",
        "adreça":{
            "carrer":"Ravella",
            "cp": "08966", 
            "id_localitat":3,
            "id_provincia":1
        },
        "telèfon":"933993333"
    },
    {
        "_id":7,
        "nom":"Julia",
        "cognom": "Stuard",
        "adreça":{
            "carrer":"Diagonal", 
            "cp":"08977", 
            "id_localitat":4,
            "id_provincia":2
        },
        "telèfon":"933994333"
    },
    {
        "_id":8,
        "nom":"Daniel", 
        "cognom":"Eduard",
        "adreça":{
            "carrer":"Barcelona", 
            "cp":"08988", 
            "id_localitat":4,
            "id_provincia":2
        },
        "telèfon":"933194333"
    },
    {
        "_id":9,
        "nom":"Pere",
        "cognom": "Perez",
        "adreça":{
            "carrer":"Valencia",
            "cp": "08999", 
            "id_localitat":5,
            "id_provincia":2
        },
        "telèfon":"933941111"
    },
    {
        "_id":10,
        "nom":"Felix",
        "cognom": "Lopez",
        "adreça":{
            "carrer":"Girona", 
            "cp":"08111", 
            "id_localitat":5,
            "id_provincia":2
        },
        "telèfon":"933999999"
    },
    {
        "_id":11,
        "nom":"Josep", 
        "cognom":"Agag",
        "adreça":{
            "carrer":"Balaguer", 
            "cp":"08222", 
            "id_localitat":6,
            "id_provincia":2
        },
        "telèfon":"933991213"
    },
    {
        "_id":12,
        "nom":"Jorge", 
        "cognom":"Bonilla",
        "adreça":{
            "carrer":"Bolivia", 
            "cp":"08444", 
            "id_localitat":7,
            "id_provincia":3
        },
        "telèfon":"933997843"
    },
    {
        "_id":13,
        "nom":"Raul", 
        "cognom":"Aznar",
        "adreça":{
            "carrer":"Ciutat",
            "cp": "08222", 
            "id_localitat":6,
            "id_provincia":2
        },
        "telèfon":"933996711"
    },
    {
        "_id":14,
        "nom":"Albert",
        "cognom": "Biel",
        "adreça":{
            "carrer":"Carders", 
            "cp":"08333", 
            "id_localitat":7,
            "id_provincia":3
        },
        "telèfon":"933997474"
    },
    {
        "_id":15,
        "nom":"Jordi",
        "cognom": "Torrente",
        "adreça":{
            "carrer":"Peru", 
            "cp":"08555", 
            "id_localitat":8,
            "id_provincia":3
        },
        "telèfon":"933992212"
    },
    {
        "_id":16,
        "nom":"Rocio",
        "cognom": "Dieguez",
        "adreça":{
            "carrer":"Melilla",
            "cp": "08666", 
            "id_localitat":8,
            "id_provincia":3
        },
        "telèfon":"933997321"
    },
    {
        "_id":17,
        "nom":"Jose Maria",
        "cognom": "Ceuta",
        "adreça":{
            "carrer":"Pere IV", 
            "cp":"08777", 
            "id_localitat":9,
            "id_provincia":3
        },
        "telèfon":"933991212"
    },
    {
        "_id":18,
        "nom":"Julian",
        "cognom": "Aroca",
        "adreça":{
            "carrer":"Carolines", 
            "cp":"08888", 
            "id_localitat":9,
            "id_provincia":3
        },
        "telèfon":"933994343"
    },
    {
        "_id":19,
        "nom":"Anna", 
        "cognom":"Aroa",
        "adreça":{
            "carrer":"Almirall Cervera",
            "cp": "08999", 
            "id_localitat":10,
            "id_provincia":4
        },
        "telèfon":"933996542"
    },
    {
        "_id":20,
        "nom":"Olga",
        "cognom": "Niam",
        "adreça":{
            "carrer":"Aragó", 
            "cp":"08232",
            "id_localitat":10,
            "id_provincia":4
        },
        "telèfon": "933992221"
    },
    {
        "_id":21,
        "nom":"Montse", 
        "cognom":"Estres",
        "adreça":{
            "carrer":"La Forja", 
            "cp":"08222", 
            "id_localitat":11,
            "id_provincia":4
        },
        "telèfon":"933993312"
    },
    {
        "_id":22,
        "nom":"Mercè", 
        "cognom":"Montserrat",
        "adreça":{
            "carrer":"Aribau", 
            "cp":"08333",
            "id_localitat":11,
            "id_provincia":4
        },
        "telèfon": "933995434"
    },
    {
        "_id":23,
        "nom":"Agata",
        "cognom": "Achilipu",
        "adreça":{
            "carrer":"Angli", 
            "cp":"08444", 
            "id_localitat":12,
            "id_provincia":4
        },
        "telèfon":"933994567"
    },
    {
        "_id":24,
        "nom":"Mia",
        "cognom": "Del Rio",
        "adreça":{
            "carrer":"Mallorca", 
            "cp":"08111", 
            "id_localitat":12,
            "id_provincia":4
        },
        "telèfon":"933994567"
    }
]);
db.empleats.insert([
    {
        _id:1,
        nom:"Pere",
        cognom:"Feliu",
        nif:"123456781B",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:2
    }
    ,
    {
        _id:2,
        nom:"Joan",
        cognom:"Garci",
        nif:"123456781C",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:1
    }
    ,
    {
        _id:3,
        nom:"Joan",
        cognom:"Feliu",
        nif:"123456781D",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:2
    }
    ,
    {
        _id:4,
        nom:"Mari",
        cognom:"Garci",
        nif:"123456789E",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:2
    }
    ,
    {
        _id:5,
        nom:"Luis",
        cognom:"Ruina",
        nif:"123456789F",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:3
    }
    ,
    {
        _id:6,
        nom:"Fele",
        cognom:"Perez",
        nif:"123456789G",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:3
    }
    ,
    {
        _id:7,
        nom:"Raul",
        cognom:"Gomez",
        nif:"123456789H",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:4
    }
    ,
    {
        _id:8,
        nom:"Kali",
        cognom:"Bueno",
        nif:"123456789J",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:4
    }
    ,
    {
        _id:9,
        nom:"Coli",
        cognom:"Lurba",
        nif:"123456789I",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:5
    }
    ,
    {
        _id:10,
        nom:"Saul",
        cognom:"Carme",
        nif:"123456789K",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:5
    }
    ,
    {
        _id:11,
        nom:"Wais",
        cognom:"Sanch",
        nif:"123456789L",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:6
    }
    ,
    {
        _id:12,
        nom:"Jaul",
        cognom:"Feliu",
        nif:"123456789M",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:6
    }
    ,
    {
        _id:13,
        nom:"Real",
        cognom:"Farci",
        nif:"123456789N",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:7
    }
    ,
    {
        _id:14,
        nom:"Tere",
        cognom:"Garci",
        nif:"123456789O",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:7
    }
    ,
    {
        _id:15,
        nom:"Toni",
        cognom:"Ruina",
        nif:"123456789P",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:8
    }
    ,
    {
        _id:16,
        nom:"Juli",
        cognom:"Perez",
        nif:"123456789Q",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:8
    }
    ,
    {
        _id:17,
        nom:"Rafa",
        cognom:"Gomez",
        nif:"123456789R",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:9
    }
    ,
    {
        _id:18,
        nom:"Marc",
        cognom:"Bueno",
        nif:"123456789T",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:9
    }
    ,
    {
        _id:19,
        nom:"Alba",
        cognom:"Lurba",
        nif:"123456789Y",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:10
    }
    ,
    {
        _id:20,
        nom:"Sara",
        cognom:"Carme",
        nif:"123456789I",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:10
    }
    ,
    {
        _id:21,
        nom:"Dani",
        cognom:"Sanch",
        nif:"123456789O",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:11
    }
    ,
    {
        _id:22,
        nom:"Luis",
        cognom:"Feliu",
        nif:"123456789A",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:11
    }
    ,
    {
        _id:23,
        nom:"Fele",
        cognom:"Feliu",
        nif:"123456789S",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:12
    }
    ,
    {
        _id:24,
        nom:"Coli",
        cognom:"Bueno",
        nif:"123456789D",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:12
    }
    ,
    {
        _id:25,
        nom:"Wais",
        cognom:"Bueno",
        nif:"123456789F",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:13
    }
    ,
    {
        _id:26,
        nom:"Rafa",
        cognom:"Garci",
        nif:"123456789G",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:13
    }
    ,
    {
        _id:27,
        nom:"Raul",
        cognom:"Feliu",
        nif:"123456789H",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:14
    }
    ,
    {
        _id:28,
        nom:"Joan",
        cognom:"Ajure",
        nif:"123456789J",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:14
    }
    ,
    {
        _id:29,
        nom:"Toni",
        cognom:"Ajure",
        nif:"123456789K",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:15
    }
    ,
    {
        _id:30,
        nom:"Tere",
        cognom:"Ajure",
        nif:"123456789L",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:15
    }
    ,
    {
        _id:31,
        nom:"Juli",
        cognom:"Gomez",
        nif:"123456789Z",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:16
    }
    ,
    {
        _id:32,
        nom:"Real",
        cognom:"Gomez",
        nif:"123456789X",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:16
    }
    ,
    {
        _id:33,
        nom:"Marc",
        cognom:"Gomez",
        nif:"123456789V",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:17
    }
    ,
    {
        _id:34,
        nom:"Alba",
        cognom:"Feliu",
        nif:"123456789B",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:17
    }
    ,
    {
        _id:35,
        nom:"Sara",
        cognom:"Feliu",
        nif:"123456789N",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:18
    }
    ,
    {
        _id:36,
        nom:"Dani",
        cognom:"Garci",
        nif:"123456789M",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:18
    }
    ,
    {
        _id:37,
        nom:"Luis",
        cognom:"Juane",
        nif:"123456781A",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:19
    }
    ,
    {
        _id:38,
        nom:"Joan",
        cognom:"Juane",
        nif:"123456781Q",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:19
    }
    ,
    {
        _id:39,
        nom:"Pere",
        cognom:"Lopez",
        nif:"123456781W",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:20
    }
    ,
    {
        _id:40,
        nom:"Said",
        cognom:"Lopez",
        nif:"123456781E",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:20
    }
    ,
    {
        _id:41,
        nom:"Miki",
        cognom:"Ajure",
        nif:"123456781R",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:21
    }
    ,
    {
        _id:42,
        nom:"Marc",
        cognom:"Waist",
        nif:"123456781T",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:21
    }
    ,
    {
        _id:43,
        nom:"Susi",
        cognom:"Raule",
        nif:"123456781Y",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:22
    }
    ,
    {
        _id:44,
        nom:"Juli",
        cognom:"Juane",
        nif:"123456781U",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:22
    }
    ,
    {
        _id:45,
        nom:"Mimi",
        cognom:"Gomez",
        nif:"123456781I",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:23
    }
    ,
    {
        _id:46,
        nom:"Elia",
        cognom:"Sanch",
        nif:"123456781O",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:23
    }
    ,
    {
        _id:47,
        nom:"Oric",
        cognom:"Feliu",
        nif:"123456781P",
        telèfon:"931234567",
        carrec:"Cuiner",
        id_botiga:24
    }
    ,
    {
        _id:48,
        nom:"Xena",
        cognom:"Garci",
        nif:"123456781A",
        telèfon:"931234567",
        carrec:"Repartidor",
        id_botiga:24
    }
    
]);
db.categories_pizza.insert([
    {
        _id:1,
        nom:"tot l'any"
    }
    ,
    {
        _id:2,
        nom:"di d'Italia"
    }
]);
db.productes.insert([
    {
        _id:1,
        nom:"coca-cola",
        descripció:"Beguda", 
        preu:1.90
    }
    ,
    {
        _id:2,
        nom:"fanta",
        descripció:"Beguda",
        preu: 1.80
    }
    ,
    {
        _id:3,
        nom:"completa",
        descripció:"Hamburguesa", 
        preu:5.90
    }
    ,
    {
        _id:4,
        nom:"solo queso",
        descripció:"Hamburguesa", 
        preu:4.50
    }
    ,
    {
        _id:5,
        nom:"Margarita",
        descripció:"Pizza",
        preu: 20.90,
        id_categoria_pizza:1
    }
    ,
    {
        _id:6,
        nom:"Barbacoa",
        descripció:"Pizza",
        preu: 23.90,
        id_categoria_pizza:1
    }
    ,
    {
        _id:7,
        nom:"Pepperoni",
        descripció:"Pizza", 
        preu:24.90,
        id_categoria_pizza:2
    }
    ,
    {
        _id:8,
        nom:"4 formatges",
        descripció:"Pizza", 
        preu:25.90,
        id_categoria_pizza:2
    }
]);
db.comandes.insert([
    {
        _id:1,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:1,
        id_empleat:2,
        data_hora_lliurament:ISODate("2020-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:3
            }
        ]        
    }
    ,
    {
        _id:2,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:1,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:3,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:1,
        id_empleat:6,
        data_hora_lliurament:ISODate("2022-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    ,
    {
        _id:4,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:2,
        id_empleat:6,
        data_hora_lliurament:ISODate("2021-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:5,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:2,
        id_empleat:4,
        data_hora_lliurament:ISODate("2022-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:3
            }
        ]        
    }
    ,
    {
        _id:6,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:3,
        id_empleat:4,
        data_hora_lliurament:ISODate("2021-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:7,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:4,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    ,
    {
        _id:8,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:4,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:9,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:5,
        id_empleat:8,
        data_hora_lliurament:ISODate("2022-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:3
            }
        ]        
    }
    ,
    {
        _id:10,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:5,
        id_empleat:10,
        data_hora_lliurament:ISODate("2021-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:11,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:6,
        id_empleat:10,
        data_hora_lliurament:ISODate("2020-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    ,
    {
        _id:12,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:7,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:13,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:8,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:14,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:9,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:15,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:9,
        id_empleat:10,
        data_hora_lliurament:ISODate("2022-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    ,
    {
        _id:16,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:10,
        id_empleat:12,
        data_hora_lliurament:ISODate("2022-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:17,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:11,
        id_empleat:12,
        data_hora_lliurament:ISODate("2020-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:3
            }
        ]        
    }
    ,
    {
        _id:18,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:12,
        id_empleat:14,
        data_hora_lliurament:ISODate("2020-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:19,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:13,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    ,
    {
        _id:20,
        data_hora_comanda:ISODate("2022-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:14,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:6
            }
        ]        
    }
    ,
    {
        _id:21,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:15,
        id_empleat:16,
        data_hora_lliurament:ISODate("2020-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:3
            }
        ]        
    }
    ,
    {
        _id:22,
        data_hora_comanda:ISODate("2021-12-24 10:45:12"),
        tipus_entrega:"domicili",
        id_client:16,
        id_empleat:18,
        data_hora_lliurament:ISODate("2021-12-24 10:45:12"),
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:4
            }
        ]        
    }
    ,
    {
        _id:23,
        data_hora_comanda:ISODate("2020-12-24 10:45:12"),
        tipus_entrega:"botiga",
        id_client:17,
        llista_productes:[
            {
                quantitat:2,
                id_procucte:1
            },
            {
                quantitat:1,
                id_procucte:2
            },
            {
                quantitat:3,
                id_procucte:5
            }
        ]        
    }
    
]);